import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Pulse coding",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen font-sans antialiased", fontSans.variable)}>
        <div className="wrapper flex flex-col h-screen">
          {/* Navbar */}
          <Navbar/>
          <main className="flex-1 flex flex-col justify-center">{children}</main>
          {/* Footer */}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
